version: '3.7'

services:
  app:
    container_name: dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
