FROM php:8.1.19

ENV APP_ENV=dev XDEBUG_MODE=off

VOLUME /app/var/

RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"

COPY --link frankenphp/conf.d/app.dev.ini $PHP_INI_DIR/conf.d/

RUN apt-get update && apt-get install -y \
    git \
    unzip \
    libicu-dev \
    libzip-dev \
    && docker-php-ext-install intl zip pdo pdo_mysql

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /app

COPY --link ./composer.json ./

# Install Symfony dependencies using Composer
RUN composer install

COPY --link . .

RUN rm -rf frankenphp/

EXPOSE 8080

CMD php -S 0.0.0.0:8080 public/index.php
